services:
  database:
    image: postgres:17.1
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_KEY}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - bevpro-data:/var/lib/postgresql/data
    container_name: bevpro_database

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    environment:
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - '5050:80'
    volumes:
      - bevpro-data:/var/lib/postgresql/data
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
      - ./pgpass:/pgpass


  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bevpro_api
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DATABASE_HOST=database
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_KEY=${DATABASE_KEY}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_NAME=${DATABASE_NAME}
    ports:
      - '8000:${PORT}'
    depends_on:
      - database
    volumes:
      - ./src:/app/src
volumes:
  bevpro-data:
  pgadmin-data:

